using System;

public enum Direction{
	UP, DOWN, LEFT, RIGHT, DIAG_UP_RIGHT, DIAG_UP_LEFT, DIAG_BOT_LEFT, DIAG_BOT_RIGHT
}
public enum Sector{
	TOPLEFT, TOPMID, TOPRIGHT, MIDLEFT, MIDMID, MIDRIGHT, BOTLEFT, BOTMID, BOTRIGHT
}

